[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Jonas Vander Vennet <jonas.vdv@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
